### PR TITLE
 UPDATE README AND UPLOAD MISTRAL AND LLAMA3 NIM notebooks

### PR DESCRIPTION
**Pull request by nithiyn**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by JoeyTPChou** [comment]
1. It looks like 99% of the code can be reused, can we use this way https://saturncloud.io/blog/how-to-import-jupyter-notebooks-to-another-jupyter-notebook/ to avoid having too much duplication?
2. Please align the filename format.

**Comment by JoeyTPChou** [comment]
1. Please explain a bit the purpose of having an `NGC_API_KEY` if the image is pulled from ECR.
2. Please check if we can use `boto3` instead of calling subprocess for aws cli

**Comment by nithiyn** [comment]
> 1. Please explain a bit the purpose of having an `NGC_API_KEY` if the image is pulled from ECR.
 completed
> 2. Please check if we can use `boto3` instead of calling subprocess for aws cli
we need the subprocess for cli to tag and push the image to ecr so we aren't able to use boto3

**Comment by nithiyn** [comment]
> 1. It looks like 99% of the code can be reused, can we use this way https://saturncloud.io/blog/how-to-import-jupyter-notebooks-to-another-jupyter-notebook/ to avoid having too much duplication?
> 2. Please align the filename format.
completed

**Review by amanshanbhag — APPROVED** [review]
Resolved

**Pull request merged**
